name: Deploy project 

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup & Build
      env: 
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        # setup private key
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        ssh-keyscan -H "$SERVER_IP" > ~/.ssh/known_hosts
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa 

        # debug ssh
        ssh -v "github@$SERVER_IP:/var/www/audio.lordmushroom.dev"

        # deploy our code
        rsync -rv app/ "github@$SERVER_IP:/var/www/audio.lordmushroom.dev/" --delete
